spring:
  application:
    name: ingredient-client
  cloud:
    config:
      uri: http://localhost:8888
---

spring:
  profiles: indredient-client-1
  application:
    name: ingredient-client

---
spring:
  profiles: indredient-client-2
  application:
    name: ingredient-client

---
spring:
  profiles: indredient-client-3
  application:
    name: ingredient-client
